FROM ubuntu
RUN apt-get update && apt-get install -y httpie build-essential libssl-dev git && rm -rf /var/lib/apt/lists/* \
&& git clone https://github.com/wg/wrk.git wrk \
&& cd wrk && make \
&& cp wrk /usr/local/bin
CMD bash